<?php

/**
 * @file
 * ldnddev Accordion module file.
 */

/**
 * Implements hook_theme().
 */
function ldnddev_accordion_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ldnddev_accordion' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ldnddev_accordion_item' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_accordion' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_accordion_item' => [
      'base hook' => 'paragraph',
    ],
  ];
}
